version: '3.7'

services:

  users:
    container_name: users
    build:
      context: ./services/users
      dockerfile: Dockerfile.prod
    ports:
      - 5001:5000
    environment:
      - FLASK_ENV=production
      - APP_SETTINGS=project.config.ProductionConfig
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_prod
      - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test
      - SECRET_KEY=my_precious
    depends_on:
      - users-db

  users-db:
    build:
      context: ./services/users/project/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  client:
    build:
      context: ./services/client
      dockerfile: Dockerfile.prod
      args:
        - NODE_ENV=production
        # http://users:5000/api doesn't work because React app makes requests to the users service from the browser
        # (e.g. outside of the container)
        - REACT_APP_USERS_SERVICE_URL=http://localhost:5001/api
    ports:
      - 8080:8000
    # env_file:
    #   - ./.env.prod
    depends_on:
      - users
